### ISSUE TITLE
cannot compile with urho3d

### ISSUE THREAD

**Issue by yushli** [LucKeyProductions/KO#1]
many errors occur while compiling with the default urho3d. Would you like to fix them? Thanks. 
The screen shots look quite nice.

**Comment by Modanung** [comment]
I will. Don't get too excited though. Game play is still pretty much non-existent.
Please check out [hēXōn](https://github.com/LucKeyProductions/heXon) if you haven't already. Some recent changes made it compile for others as well, I still need to apply the same changes to KO.

**Comment by Modanung** [comment]
Should be fixed with latest commit.

**Comment by yushli** [comment]
Thanks for the effort. I will try when I have time and let you know if it works. Keep up the good work!
